export enum ApiErrorTypeEnum {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  CONFLICT_ERROR = 'CONFLICT_ERROR',
  UNAUTHORIZED_EXCEPTION = 'UNAUTHORIZED_EXCEPTION',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  UNPROCESSABLE_ENTITY_ERROR = 'UNPROCESSABLE_ENTITY_ERROR',
}

export type ApiErrorType = `${ApiErrorTypeEnum}`;
