export interface ISupplier {
  id: string;
  partnerId: string;
  partnerName: string;
  customerId: string;
  customerName: string;
  customerDomainName: string;
  customerCountry: string;
  mpnId: number;
  tier2MpnId: number;
  invoiceNumber: string;
  productId: string;
  skuId: string;
  availabilityId: string;
  skuName: string;
  productName: string;
  publisherName: string;
  publisherId: string | null;
  subscriptionDescription: string | null;
  subscriptionId: string;
  chargeStartDate: string;
  chargeEndDate: string;
  usageDate: string;
  meterType: string;
  meterCategory: string;
  meterId: string;
  meterSubCategory: string;
  meterName: string;
  meterRegion: string | null;
  unit: string;
  resourceLocation: string;
  consumedService: string;
  resourceGroup: string;
  resourceURI: string;
  chargeType: string;
  unitPrice: number;
  quantity: number;
  unitType: string;
  billingPreTaxTotal: number;
  billingCurrency: string;
  pricingPreTaxTotal: number;
  pricingCurrency: string;
  serviceInfo1: string | null;
  serviceInfo2: string | null;
  tags: Record<string, string> | null;
  additionalInfo: Record<string, string> | null;
  effectiveUnitPrice: number;
  pctoBCExchangeRate: number;
  pctoBCExchangeRateDate: string;
  entitlementId: string;
  entitlementDescription: string;
  partnerEarnedCreditPercentage: number;
  creditPercentage: number;
  creditType: string;
  benefitOrderId: string | null;
  benefitId: string | null;
  benefitType: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}
